//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class VendorRegister
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.Label lblMessage;
    protected global::System.Web.UI.WebControls.TextBox txtName;
    protected global::System.Web.UI.WebControls.TextBox txtEmail;
    protected global::System.Web.UI.WebControls.TextBox txtPassword;
    protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
    protected global::System.Web.UI.WebControls.TextBox txtLocation;
    protected global::System.Web.UI.WebControls.Button btnRegister;
}
